
server.port=${SERVER_PORT:5000}

server.ssl.enabled=${SSL_ENABLED:true}
server.ssl.key-store-type=${SSL_KEY_STORE_TYPE:PKCS12}
server.ssl.key-store=${SSL_KEY_STORE:keystores/ecikeystore.p12}
server.ssl.key-store-password=${SSL_KEY_STORE_PASSWORD:123456}
server.ssl.key-alias=${SSL_KEY_ALIAS:ecikeypair}

spring.data.mongodb.uri=${MONGODB_URI:}